[book]
authors = ["Bram Gotink"]
language = "en"
multilingual = false
src = "src"
title = "KDL"

[preprocessor.version]
command = "preprocessors/version.js"

[output.html]
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/bgotink/kdl"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/bgotink/kdl/edit/main/documentation/{path}"
