name: Publish website
on: workflow_dispatch

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Set up

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install npm dependencies
        run: |
          yarn install --immutable
      - name: Install mdbook
        run: |
          curl -fSsL https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz | tar -xvz -C ~/.cargo/bin

      # Publish website

      - name: Build website
        env:
          MDBOOK_OUTPUT__HTML__SITE_URL: /kdl/
        run: |
          yarn book
      - name: Upload website
        uses: actions/upload-pages-artifact@v3
        with:
          path: documentation/book
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
