name: Publish website
on: workflow_dispatch

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Set up

      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true
      - uses: yarnpkg/setup-action@c9778d0717d1b46cf29f06ae5ae5ad41c1bb1c1a
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24.x

      - name: Install npm dependencies
        env:
          YARN_GITHUB_RELEASE_TOKEN: ${{ github.token }}
        run: |
          yarn install --immutable

      # Publish website

      - name: Build website
        env:
          MDBOOK_OUTPUT__HTML__SITE_URL: /kdl/
        run: |
          yarn book
      - name: Upload website
        uses: actions/upload-pages-artifact@v5
        with:
          path: documentation/book
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
