on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

name: "Test"
jobs:
  validations:
    name: Install and validate dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: yarnpkg/setup-action@c9778d0717d1b46cf29f06ae5ae5ad41c1bb1c1a
      - uses: actions/setup-node@v7
        with:
          node-version: 24.x
          cache: yarn

      - name: Install
        run: |
          yarn install --immutable

      - name: Check for duplicate dependencies (fix w/ `yarn dedupe`)
        run: |
          yarn dedupe --check

      - if: ${{ github.event_name == 'pull_request' }}
        name: Review Dependencies
        uses: actions/dependency-review-action@v5

      - name: 'Check for formatting errors (fix w/ "yarn prettier --write path/to/file")'
        run: |
          yarn prettier --check .

      - name: Build
        run: |
          yarn build

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - 22.x
          - 24.x
          - 26.x

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
          persist-credentials: false
      - uses: yarnpkg/setup-action@c9778d0717d1b46cf29f06ae5ae5ad41c1bb1c1a
      - uses: actions/setup-node@v7
        with:
          node-version: ${{matrix.node}}
          cache: yarn

      - name: Install
        run: |
          yarn install --immutable

      - name: Run tests
        run: |
          yarn test

      - name: Run kdl-test
        run: |
          gh release download -O- --repo kdl-org/kdl-test \
            --pattern '*-linux-x86_64.tar.gz' \
            | tar xvz

          scripts/kdl-test.sh
